title: Jekyll Serial Programmer
markdown: kramdown

# for atom feed
author:
  name: Tobias Wothge
  email: tobi18991@users.noreply.github.com

# Theme options
show_homepage: true # Set to true if you want to have a static front page
show_excerpts: true # Set to true if excerpts of posts should be shown on the blog page

# Jekyll options
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections:
  pages:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
      permalink: /:title/
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
      navigation: /blog/

exclude: ["screenshots", "sitemap.xml", "feed.xml", "LICENSE", "README.md"]
