title: Jekyll Serial Programmer
# url: https://www.yourdomain.com # Do not uncomment when using GitHub Pages
# baseurl: /test # Do not uncomment when using GitHub Pages
markdown: kramdown

# for atom feed
author:
  name: Tobias Wothge
  email: tobi18991@users.noreply.github.com

# Theme options
show_homepage: true # Set to true if you want to have a static front page
show_excerpts: true # Set to true if excerpts of posts should be shown on the blog page
favicon: /assets/images/avatar.png # Set to the relative path where the favicon is stored
redirect_to_https: true # If true, requests on HTTP/80 will be redirected to HTTPS/443 (.htaccess file)
include_hsts: true # If true, the Strict-Transport-Security header will be appended to requests on HTTPS/443 (.htaccess file)

# Jekyll options
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections:
  pages:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
      permalink: /:title/
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
      navigation: /blog/

exclude: ["screenshots", "sitemap.xml", "feed.xml", "LICENSE", "README.md"]
